name: CI - Angular
on:
  push:
    branches: [dev, staging, main]
  pull_request:
    branches: [dev, staging, main]

permissions:
  contents: read

jobs:
  lint-and-build:
    name: Lint & Build Angular
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: plateformK/package-lock.json # Sans le ./ au début

      - name: Install dependencies
        working-directory: ./plateformK
        run: npm ci --legacy-peer-deps

      - name: Run ESLint
        working-directory: ./plateformK
        run: npm run lint

      - name: Build Angular app
        working-directory: ./plateformK
        run: npm run build -- --configuration=production
